---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quotes-prod-backend
  namespace: argo-cd
  annotations:
    argocd-image-updater.argoproj.io/image-list: thabelo/quotes-backend:~v0.1
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Thab310/quotes-infrastructure.git
    targetRevision: main
    path: overlays/quotes-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
---
