---
# backend
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quotes-prod-backend
  namespace: argo-cd
  annotations:
    argocd-image-updater.argoproj.io/image-list: thabelo/quotes-backend:~v0.1
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Thab310/quotes-infrastructure.git
    targetRevision: main
    path: overlays/prod/quotes-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
---
# frontend
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quotes-prod-frontend
  namespace: argo-cd
  annotations:
    argocd-image-updater.argoproj.io/image-list: thabelo/quotes-frontend:~v0.1
    argocd-image-updater.argoproj.io/write-back-method: git
    notifications.argoproj.io/subscribe.on-deployed.slack: alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: alerts
    #notifications.argoproj.io/subscribe.on-sync-succeeded.slack: alerts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Thab310/quotes-infrastructure.git
    targetRevision: main
    path: overlays/prod/quotes-frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      allowEmpty: false
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true